### ISSUE TITLE
Not being able to search for zip files via the API

### ISSUE THREAD

**Issue by azzy9** [azzy9/plugin.git.browser#4]
Looking up trying to get other search methods working,
Most users use github to create repos rather than source control, so the files are within the repo rather the releases.

I was wondering why when I search a repo no results are returned for zip files,
The answer:

- Vendored and generated code is excluded
- **Empty files and files over 350 kiB are excluded**
- Only UTF-8 encoded files are indexed
- Very large repositories may not be indexed

So the search/code api endpoint is useless for our use.

@joeuhren I think we have to rely on your method in your previous commit to get the latest release for now until an alternative is found

**Comment by joeuhren** [comment]
@azzy9 can you share 1-2 github links to plugins that don't use releases so I have something to test against? There must be an api or 2 we can use to get those working as well

**Comment by azzy9** [comment]
Most Kodi plugin developers use GitHub to host their repo, so do not use the release section
e.g.
[https://github.com/nemesis668/repository.streamarmy18-19/tree/main/zips](https://github.com/nemesis668/repository.streamarmy18-19/tree/main/zips)
[https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips](https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips)

**Comment by azzy9** [comment]
if we know the user, repo and branch name we can get a list of filenames and then search for the zips in that:
[https://api.github.com/repos/nemesis668/repository.streamarmy18-19/git/trees/main?recursive=1](https://api.github.com/repos/nemesis668/repository.streamarmy18-19/git/trees/main?recursive=1)

**Comment by joeuhren** [comment]
@azzy9 take a look at my newest commit. The "search by repo title" option now first searches the release zips as it was doing earlier and also now uses the /trees api you indicated above to get the complete file list and then add all the zip files it finds there. It's working great for me in both examples now and quite fast. I think this issue can be closed.

**Comment by azzy9** [comment]
Not able to test it yet, but having a look at it, it looks awesome. I will join working on it soon, but been doing other things lately 👍

**Comment by karlo2105** [comment]
@joeuhren
Could you give me a hint how to obtain zip results from repos ?

**Comment by joeuhren** [comment]
@karlo2105 the plugin is still a WIP so not everything works yet. Probably the easiest way to get it working right now is to download and install [plugin.git.browser-2.0.0.alpha.zip](https://github.com/azzy9/plugin.git.browser/releases/download/v2.0.0/plugin.git.browser-2.0.0.alpha.zip) in Kodi. Then download the newest copy of the source code from https://github.com/azzy9/plugin.git.browser/archive/refs/heads/master.zip and extract that overtop of the installed plugin to update it (%appdata%\Kodi\addons\plugin.git.browser in windows for example).

The only option that works right now is "Search by Github Repository Title", but that should get you going for now until we have time to finish restoring the rest of the functionality.

**Comment by karlo2105** [comment]
I already updated latest gitbrowser build but i didn't manage to obtain zip results through repos search. Could you give working example how to search?

**Comment by joeuhren** [comment]
@karlo2105 only the "Search by Github Repository Title" works. You enter the name of the github repo where the plugin you want is housed and it will show you the zip files from that repo and allow you to install whatever is available. For example, If you would like to install the Netflix plugin from https://github.com/CastagnaIT/plugin.video.netflix you would enter the repo name of "plugin.video.netflix" and then click on the zip file that appears when the search is complete to install it.

Also, the git browser plugin doesn't work without a github api key. If you haven't done so already, it is required that you get your own github api key and enter it into the git browser General settings, otherwise you will only get errors when trying to search.

Hopefully that helps. If not, please let me know the url of the github repo you are trying to use which is not working to see if I have the same problems on my end.

**Comment by karlo2105** [comment]
@joeuhren 
Could you give me a hint how to set github api key into gitbrowser ?
I managed to install latest Rumble release from @azzy9 through gitbrowser. However, gitbrowser doesn't propose development version nor @nirvana-7777 repo. 
How to install with gitbrowser latest fix from development zip : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore
I didn't find where does gitbrowser store locally downloaded plugin.

**Comment by joeuhren** [comment]
@karlo2105 I was wrong earlier by saying that the git browser doesn't work without an api key as you obviously found out, but you are given very few credits per day without it and this will limit the amount of credits you can use per hour from 60 to 5000 with an api key. Most times many credits are used for a single search within the git browser plugin to enumerate many different repos and/or users for example. You can read more about github rate limits here: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

> Could you give me a hint how to set github api key into gitbrowser ?

To generate your own api key you first need your own (free or paid) github account. Log in to github and visit this page: [https://github.com/settings/personal-access-tokens/new](https://github.com/settings/personal-access-tokens/new). You shouldn't require any special permissions so you can keep the default "Public repositories (read-only)" option and give it an expiration date far in the future if you dont want to have to keep regenerating a new one every time it expires. Once you are given the api key, you can plug it into the "Personal Access Token" field in the git browser settings to increase the amount of searches you can do:
![image](https://github.com/azzy9/plugin.git.browser/assets/46763106/373f0b50-efca-47e7-8207-e2d9b8ae8470)

> I managed to install latest Rumble release from @azzy9 through gitbrowser. However, gitbrowser doesn't propose development version nor @nirvana-7777 repo.

Right now the git browser first searches for release zip files such as you can find here: [https://github.com/azzy9/plugin.video.rumble/releases](https://github.com/azzy9/plugin.video.rumble/releases).  If no zip files are found it will then attempt to look for zip files within the default repo such as you can find here: [https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips/release/catchuptvandmore.kodi.release](https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips/release/catchuptvandmore.kodi.release). That's as far as it goes for now so if zip files aren't found in those 2 places, it will continue to the next repo and try again. The releases section is global to all branches and I feel that usually searching the default branch is "good enough" although perhaps a new option can be added in the future that allows searching a specific branch or all branches for a particular repo.

I did a quick look through some of the repos provided by user nirvana-7777 and it seems like only raw source code is provided for most of those and there aren't really any releases or ready-to-go zip files which are compatible with the git browser at this time. The git browser could possibly be updated in the future to look for an addon.xml file and pull in all the files from the directory although that would likely use lots of api credits to download hundreds of individual files for a single plugin. For now, I would recommend reaching out to nirvana-7777 and ask them to provide a release zip file either in the releases section or within the repo files themselves to make it compatible with the current version of the git browser, and/or ask how else they recommend to install their plugins directly from within kodi. Of course, you could always fork the repos you want from nirvana-7777 and upload your own release zip file and then browse for your own github username with the git browser, although that might defeat the purpose a bit by having you do some manual work outside of kodi, but its still a valid workaround for now.

> How to install with gitbrowser latest fix from development zip : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore

Again, the git browser is currently only compatible with zip files so in this case it will pull the 2 zip files from [https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases) from Aug 28, 2022 which I assume are not the "fixed" version you are asking about. The readme for that plugin also has a setup guide which mentions installing from the official repo which you can read more about here: [https://catch-up-tv-and-more.github.io/installation/](https://catch-up-tv-and-more.github.io/installation/). If the official kodi repo for the plugin and/or github repo does not supply a proper zip file that is ready to install then for now you will need to download and merge the updated files yourself by hand as the git browser does not do this currently.

> I didn't find where does gitbrowser store locally downloaded plugin.

Plugins that are installed via the git browser are first downloaded to the kodi data directory in the userdata\addon_data\plugin.git.browser\downloads directory. For example, in Windows a sample path would be C:\Users\Username\AppData\Roaming\Kodi\userdata\addon_data\plugin.git.browser\downloads. The plugin zip is extracted and installed to the addons folder in the Kodi data directory such as C:\Users\Username\AppData\Roaming\Kodi\addons\plugin.git.browser. The original zip files are deleted after installation which is probably why you cannot find it if you are looking for the plugin zip file.

Hopefully that helps.

**Comment by karlo2105** [comment]
@joeuhren 

> To generate your own api key you first need your own (free or paid) github account. Log in to github and visit this page: https://github.com/settings/personal-access-tokens/new. You shouldn't require any special permissions so you can keep the default "Public repositories (read-only)" option and give it an expiration date far in the future if you dont want to have to keep regenerating a new one every time it expires. Once you are given the api key, you can plug it into the "Personal Access Token" field in the git browser settings to increase the amount of searches you can do:

I managed to generate api key and to extend its duration till 12 months at latest. However, it took me a while to encode it in plugin settings with remote keyboard but now i am good for a year. ;-) Isn't it easier to add login field in git.browser to bypass token creation in order to get over search limitation ? Is it possible to include a feature in git.browser to auto-update plugins which were installed through it ?

> For now, I would recommend reaching out to nirvana-7777 and ask them to provide a release zip file either in the releases section or within the repo files themselves to make it compatible with the current version of the git browser, and/or ask how else they recommend to install their plugins directly from within kodi. Of course, you could always fork the repos you want from nirvana-7777 and upload your own release zip file and then browse for your own github username with the git browser, although that might defeat the purpose a bit by having you do some manual work outside of kodi, but its still a valid workaround for now.

Nirvana-7777 provides its plugins on Kodinerds forum but i have to keep an eye on it in order to have latest update. It's not a big deal but he doesn't seem to be eager to create repo. 

Thanks very much for your accurate reply.

**Comment by joeuhren** [comment]
> Isn't it easier to add login field in git.browser to bypass token creation in order to get over search limitation ?

The git browser plugin utilizes the github api which is the only legitimate way to get data directly from github programmatically. If I understand correctly, you are asking about adding a login to emulate http POST and GET requests to get data from github the same way a browser does, without restrictions. This is possible to do although it would definitely be more difficult, especially since the api method is already done and working. Not only that, screen scraping is normally against the TOS of most websites and is exactly why many bigger websites provide an api, to prevent you from needing to do such things. The api data should never really change so code can be written once that just works whereas the website interface can see slight changes on a more regular basis that can effectively break the plugin and require frequent updates and maintenance. In this case the github api is very easy to develop for and gives generous limits which should meet the needs of most users.

> Is it possible to include a feature in git.browser to auto-update plugins which were installed through it ?

I'm sure anything is possible, but that's a lot of extra plumbing that didn't exist in the original git browser from years ago. Long story short, full source code is provided for anyone that would like to add such a feature, but I feel it will be quite difficult to achieve.

> Nirvana-7777 provides its plugins on Kodinerds forum but i have to keep an eye on it in order to have latest update. It's not a big deal but he doesn't seem to be eager to create repo.

If you haven't already, I would reach out to Nirvana-7777 and ask them to also provide zip releases on their github repo. If they are already doing it on a 3rd party forum, it would only take them an extra minute to upload it to github as well. My guess is that since the git browser was only restored for newer kodi versions recently, it is very possible that they are not even aware of this being an option for making their plugins more widely and easily available to modern kodi users.

**Comment by azzy9** [comment]
Closing since original issue is sorted
